import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [esbuildSvelte({ compilerOptions: { css: "injected" } })],
});

if (prod) {
	await context.rebuild();
	copyWebappDist();
	process.exit(0);
} else {
	await context.watch();
}

/**
 * webapp:build成果物(webapp/dist)をプラグインディレクトリ配下へコピーする(design-browser-ui.md §3.4)。
 * `npm run build`は`webapp:build`をこのスクリプトより先に実行する想定(package.json)。単体で
 * `node esbuild.config.mjs production`だけを実行した場合はwebapp/distが無いためスキップし警告する。
 */
function copyWebappDist() {
	if (!fs.existsSync("webapp/dist")) {
		console.warn("Personal OS: webapp/dist not found, skipping webapp-dist copy (run `npm run webapp:build` first).");
		return;
	}
	fs.rmSync("webapp-dist", { recursive: true, force: true });
	fs.cpSync("webapp/dist", "webapp-dist", { recursive: true });
}
